common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from pybo import views
from rest_framework import routers
from pybo.views import MovieViewSet
from django.contrib.auth import views as auth_views

router = routers.DefaultRouter() 
router.register('movies',MovieViewSet) # prefix = movies , viewset = MovieViewSet

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/',include(router.urls)),
    path("admin/", admin.site.urls),
    path("pybo/", include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path
from pybo.views import MovieViewSet
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include, re_path
app_name = 'pybo'

urlpatterns = [
    #path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change-password/',auth_views.PasswordChangeView.as_view()),    
    path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    #path('question/create/', views.question_create, name='question_create'),
    path('profile/base/', views.user_profile, name='user_profile'),
    path('profile/question/', views.user_question, name='user_question'),
    path('profile/answer/', views.user_answer, name='user_answer'),
    path('profile/comment/', views.user_comment, name='user_comment'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('alexander', views.index2, name='index2'),
    path('question/craete/<str:category_name>/', views.question_create, name='question_create'),
    path('question/list/', views.index, name='index'),
    path('question/list/<str:category_name>/', views.index, name='index'),
    path('question/detail/<int:question_id>/', views.detail, name='detail'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
    
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->

{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:index' %}">질문&답변</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:index2' %}">알렉산더 사진</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/password_reset.html
<form method="post" action="{% url 'password_reset' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">회원가입</button>
</form>

templates/password_reset_done_fail.html
<h1> fail</h1>

templates/password_rest_done.html
{% extends "base.html" %}
{% block content %}
<div class="row pt-6" style="user-select: auto;">
    <div class="col-12 text-center py-5" style="user-select: auto; text-align: center; padding-top: 4.5rem;">
        <h1 class="my-5 py-5" style="user-select:auto; font-size: 3.5rem;">메일 보냄 ㅅㄱ</h1>
        <p style="user-select: auto;">메일 빨리 확인좀</p>
    </div>
</div>
{% endblock %}